// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0003_user_token.sql

package database

import (
	"context"
	"database/sql"
)

const insertUserToken = `-- name: InsertUserToken :execresult
INSERT INTO ` + "`" + `user_token` + "`" + ` (
    refresh_token,
    public_key,
    user_id,
    token_created_at,
    token_updated_at
) VALUES (?, ?, ?, NOW(), NOW())
`

type InsertUserTokenParams struct {
	RefreshToken string
	PublicKey    string
	UserID       int32
}

func (q *Queries) InsertUserToken(ctx context.Context, arg InsertUserTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUserToken, arg.RefreshToken, arg.PublicKey, arg.UserID)
}
