// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0004_role.sql

package database

import (
	"context"
	"database/sql"
)

const insertRole = `-- name: InsertRole :exec
INSERT INTO ` + "`" + `role` + "`" + ` (
    role_name,
    role_slug,
    role_description
) VALUES (?, ?, ?)
`

type InsertRoleParams struct {
	RoleName        string
	RoleSlug        string
	RoleDescription sql.NullString
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertRole, arg.RoleName, arg.RoleSlug, arg.RoleDescription)
	return err
}
