// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0006_user_profile.sql

package database

import (
	"context"
	"database/sql"
)

const insertUserProfileRegister = `-- name: InsertUserProfileRegister :execresult
INSERT INTO ` + "`" + `user_profile` + "`" + ` (
    user_id,
    user_email
) VALUES (?, ?)
`

type InsertUserProfileRegisterParams struct {
	UserID    int32
	UserEmail string
}

func (q *Queries) InsertUserProfileRegister(ctx context.Context, arg InsertUserProfileRegisterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUserProfileRegister, arg.UserID, arg.UserEmail)
}
